pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/salman-ijaz-98765/eks-jenkins-terraform.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init -input=false'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan -out=tfplan -input=false'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        // stage('Terraform Destroy') {
        //     when {
        //         expression { return params.DESTROY == true }
        //     }
        //     steps {
        //         dir('terraform') {
        //             sh 'terraform destroy -auto-approve'
        //         }
        //     }
        // }
    }

    // parameters {
    //     booleanParam(name: 'DESTROY', defaultValue: false, description: 'Check to destroy infrastructure')
    // }
}